//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace porker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("porker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_APP {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_APP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_CONFIG_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_CONFIG_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_ERR_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_ERR_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_EXEC_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_EXEC_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_EXEC_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_EXEC_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_EXECGREEN_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_EXECGREEN_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_EXECGREY_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_EXECGREY_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_GREEN {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_GREEN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_GREY {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_GREY", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_IEPAGE_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_IEPAGE_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_INFO_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_INFO_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_KEY_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_KEY_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_LEFT_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_LEFT_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_LOG_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_LOG_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_RED {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_RED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_REFRESH_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_REFRESH_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_RIGHT_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_RIGHT_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_TIMESYNC_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_TIMESYNC_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_UPDATE_24 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_UPDATE_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_USER_128 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_USER_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PK_ICO_WARN_16 {
            get {
                object obj = ResourceManager.GetObject("PK_ICO_WARN_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE浏览器.
        /// </summary>
        internal static string PK_STR_APP_NAME {
            get {
                return ResourceManager.GetString("PK_STR_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后退.
        /// </summary>
        internal static string PK_STR_BACK {
            get {
                return ResourceManager.GetString("PK_STR_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数设置.
        /// </summary>
        internal static string PK_STR_CONFIG {
            get {
                return ResourceManager.GetString("PK_STR_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://zhongbao.10085.cn:18080/.
        /// </summary>
        internal static string PK_STR_HOMEPAGE {
            get {
                return ResourceManager.GetString("PK_STR_HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页用户登录.
        /// </summary>
        internal static string PK_STR_LOG_LOGIN {
            get {
                return ResourceManager.GetString("PK_STR_LOG_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        internal static string PK_STR_LOG_NAV {
            get {
                return ResourceManager.GetString("PK_STR_LOG_NAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始对时.
        /// </summary>
        internal static string PK_STR_LOG_SYNC {
            get {
                return ResourceManager.GetString("PK_STR_LOG_SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对时失败.
        /// </summary>
        internal static string PK_STR_LOG_SYNCERR {
            get {
                return ResourceManager.GetString("PK_STR_LOG_SYNCERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对时成功！.
        /// </summary>
        internal static string PK_STR_LOG_SYNCOK {
            get {
                return ResourceManager.GetString("PK_STR_LOG_SYNCOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页登录.
        /// </summary>
        internal static string PK_STR_LOGIN {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string PK_STR_LOGIN_CMD {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名和密码登录软件。.
        /// </summary>
        internal static string PK_STR_LOGIN_DESCRIPT {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_DESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败.
        /// </summary>
        internal static string PK_STR_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登录.
        /// </summary>
        internal static string PK_STR_LOGIN_ING {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_ING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码：.
        /// </summary>
        internal static string PK_STR_LOGIN_PASS {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名：.
        /// </summary>
        internal static string PK_STR_LOGIN_USER {
            get {
                return ResourceManager.GetString("PK_STR_LOGIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始自动抢单.
        /// </summary>
        internal static string PK_STR_RUN {
            get {
                return ResourceManager.GetString("PK_STR_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示日志.
        /// </summary>
        internal static string PK_STR_SHOWLOG {
            get {
                return ResourceManager.GetString("PK_STR_SHOWLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        internal static string PK_STR_UPDATEAPP {
            get {
                return ResourceManager.GetString("PK_STR_UPDATEAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败.
        /// </summary>
        internal static string PK_STR_UPDATEERR {
            get {
                return ResourceManager.GetString("PK_STR_UPDATEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到新版本，是否要更新？新版本.
        /// </summary>
        internal static string PK_STR_UPDATEFOUND {
            get {
                return ResourceManager.GetString("PK_STR_UPDATEFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到更新.
        /// </summary>
        internal static string PK_STR_UPDATENOTFOUND {
            get {
                return ResourceManager.GetString("PK_STR_UPDATENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功！.
        /// </summary>
        internal static string PK_STR_UPDATEOK {
            get {
                return ResourceManager.GetString("PK_STR_UPDATEOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络对时.
        /// </summary>
        internal static string PK_STR_UPDATETIME {
            get {
                return ResourceManager.GetString("PK_STR_UPDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://54.223.123.174:8083/poker/auth/login.
        /// </summary>
        internal static string PK_STR_URL_LOGIN {
            get {
                return ResourceManager.GetString("PK_STR_URL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cloud.emlab.net/p/pk/.
        /// </summary>
        internal static string PK_STR_URL_UPDATE {
            get {
                return ResourceManager.GetString("PK_STR_URL_UPDATE", resourceCulture);
            }
        }
    }
}
